### PR TITLE
Dependency update

### PR DESCRIPTION
**Pull request by Zeitsperre**
This update deals with security issues arising from outdated dependencies.

### CODE REVIEW

**Comment by huard** [comment]
If it runs you're good to go.

**Comment by Zeitsperre** [comment]
Almost there. I just need to figure add "martinez-polygon-clipping" to npm and it should be fine.

**Comment by Zeitsperre** [comment]
Added missing libraries but it seems to break when selecting certain seasonal average(Invalid format +.NaNf). @tlogan2000 is posting the error output now.

**Comment by tlogan2000** [comment]
Most maps seem to be ok. Minim temp seems to crash the site... gives error below: 
I maybe will try re-running the data preparation script to see if it gets rid of the issues... 

Error: invalid format: +.NaNf
FormatSpecifier
node_modules/d3-format/src/formatSpecifier.js:13
formatSpecifier
node_modules/d3-format/src/formatSpecifier.js:7
newFormat
node_modules/d3-format/src/locale.js:19
updateMaps
src/RegionPageSpatial.js:106

  103 | var futureCellData = _.fromPairs(_.map(_.filter(this.state.spatialData, { h: this.state.horizon.id, s: this.state.scenario.id, p: this.state.percentile }), (item) => [item.c, item.v]))
  104 | 
  105 | // Reduce significant digits
> 106 | var differenceFormat = d3.format("+." + d3.precisionFixed((max - min) / 100) + "f")
  107 | var valueFormat = d3.format("." + d3.precisionFixed((max - min) / 100) + "f")
  108 | 
  109 | // Formatting for reference map

fetchData/</<
src/RegionPageSpatial.js:73

  70 |     spatialData.forEach((d) => {
  71 |       d.v = +d.v
  72 |     })
> 73 |     this.setState({ spatialData }, () => this.updateMaps(this.state.horizon, this.state.scenario))
  74 |   })
  75 | }
  76 | 

fetchData/<
src/RegionPageSpatial.js:73

  70 |     spatialData.forEach((d) => {
  71 |       d.v = +d.v
  72 |     })
> 73 |     this.setState({ spatialData }, () => this.updateMaps(this.state.horizon, this.state.scenario))
  74 |   })
  75 | }
  76 | 

This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

**Comment by grassick** [comment]
Beware: An update from version 3 to version 4 of bootstrap is very significant and requires code changes! The security problems in version 3 are minor and in this case irrelevant since it is a static site.

**Comment by grassick** [comment]
As for the NaN, I would suggest that perhaps you have a min or max value that is NaN in the data source? That would cause this particular error.

**Comment by Zeitsperre** [comment]
Closing under the advice of @grassick

**Pull request closed without merging**
